name: Release

# Run this workflow when a new tag is pushed
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Install Linker
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          working-directory: app

      - name: Build Binary
        run: cd app && make build

      - name: Package Binary
        run: |
          BINARY_NAME="amaru-pi"
          TARGET_DIR="app/target/aarch64-unknown-linux-gnu/release"
          ARCHIVE_NAME="${BINARY_NAME}-${{ github.ref_name }}-aarch64-unknown-linux-gnu.tar.gz"
          
          tar -czf "${ARCHIVE_NAME}" -C "${TARGET_DIR}" "${BINARY_NAME}"
          echo "ARCHIVE_PATH=${ARCHIVE_NAME}" >> $GITHUB_ENV

      - name: Generate Checksum
        run: sha256sum ${{ env.ARCHIVE_PATH }} > checksums.txt

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.ARCHIVE_PATH }},checksums.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          immutableCreate: true
